<?php

namespace ContainerJ2DR1mk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddChambreTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AddChambreType' shared autowired service.
     *
     * @return \App\Form\AddChambreType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddChambreType.php';

        return $container->privates['App\\Form\\AddChambreType'] = new \App\Form\AddChambreType();
    }
}
