<?php

namespace ContainerMBxGhco;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SkmlB_RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SkmlB.R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SkmlB.R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeChambreRepository' => ['privates', 'App\\Repository\\TypeChambreRepository', 'getTypeChambreRepositoryService', true],
        ], [
            'typeChambreRepository' => 'App\\Repository\\TypeChambreRepository',
        ]);
    }
}
