<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ2DR1mk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ2DR1mk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ2DR1mk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ2DR1mk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ2DR1mk\App_KernelDevDebugContainer([
    'container.build_hash' => 'J2DR1mk',
    'container.build_id' => '95db5de7',
    'container.build_time' => 1594130502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ2DR1mk');
