<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'batiment' => [[], ['_controller' => 'App\\Controller\\BatimentController::index'], [], [['text', '/batiment']], [], []],
    'chambre' => [[], ['_controller' => 'App\\Controller\\ChambreController::index'], [], [['text', '/chambre']], [], []],
    'addchambre' => [[], ['_controller' => 'App\\Controller\\ChambreController::addChambre'], [], [['text', '/chambre/addchambre']], [], []],
    'generernumerochambre' => [[], ['_controller' => 'App\\Controller\\ChambreController::getNewNumeroChambre'], [], [['text', '/chambre/generernumerochambre']], [], []],
    'listetudiant' => [[], ['_controller' => 'App\\Controller\\EtudiantController::index'], [], [['text', '/etudiant']], [], []],
    'alllistetudiant' => [[], ['_controller' => 'App\\Controller\\EtudiantController::allEtudiant'], [], [['text', '/alllistetudiant']], [], []],
    'type_bourse' => [[], ['_controller' => 'App\\Controller\\TypeBourseController::index'], [], [['text', '/type/bourse']], [], []],
    'type_chambre' => [[], ['_controller' => 'App\\Controller\\TypeChambreController::index'], [], [['text', '/type/chambre']], [], []],
    'fos_js_routing_js' => [['_format'], ['_controller' => 'fos_js_routing.controller::indexAction', '_format' => 'js'], ['_format' => 'js|json'], [['variable', '.', 'js|json', '_format', true], ['text', '/js/routing']], [], []],
];
