<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLvFAMXF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLvFAMXF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLvFAMXF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLvFAMXF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLvFAMXF\App_KernelDevDebugContainer([
    'container.build_hash' => 'LvFAMXF',
    'container.build_id' => '041fa7e9',
    'container.build_time' => 1593800903,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLvFAMXF');
